### ISSUE TITLE
Validierung der Netzwerkkonfiguration geht nicht mehr seit Git 2.19.0.windows.1

### ISSUE THREAD

**Issue by cheinema** [cheinema/minikube-bridged#1]
Die Kommandozeile
```
/d/Apps/VirtualBox/VBoxManage.exe showvminfo minikube --details --machinereadable | egrep '^nic[0-9]=' | grep -v 'none' | sort | paste -sd','
```
im Skript `minikube-run.sh` liefert seit Git 2.19.0.windows.1 nur noch `,nic2="hostonly"` statt `nic1="bridged",nic2="hostonly"` wie in Git 2.18.0.windows.1.

**Comment by cheinema** [comment]
Fehlerursache: `VBoxManage.exe` erzeugt eine Ausgabe mit CRLF-Zeilenumbrüchen. Das Kommando `egrep` hat in Git 2.18.0.windows.1 (GNU grep 3.0) die Zeilenenden im Resultat nebenbei nach LF konvertiert. In Git 2.19.0.windows.1 (GNU grep 3.1) bleibt dagegen CRLF erhalten. Schließlich kommt das abschließende `paste` nicht mit CRLF zurecht.

**Comment by cheinema** [comment]
Zum Verhalten von `paste` (unabhängig von der Git-Version):
* `echo -ne 'Line 1\nLine 2\n' | paste -sd','` (LF-Umbrüche) erzeugt `Line 1,Line 2` (OK).
* `echo -ne 'Line 1\r\nLine 2\r\n' | paste -sd','` (CRLF-Umbrüche) erzeugt `,Line 2` (Fehler).

**Comment by cheinema** [comment]
Vermutliche Ursache der Verhaltensänderung von `egrep`: http://git.savannah.gnu.org/cgit/grep.git/commit/?id=5398777784b4455aa8466c1aef48b5738b8cd626

**Comment by cheinema** [comment]
Die Lösung des Problems besteht in der Konvertierung der Ausgabe von `VBoxManage.exe` per `dos2unix` vor der Übergabe an `egrep`.

**Comment by maimArt** [comment]
Top. Danke für die schnelle Hilfe!
